import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Header from './components/Header';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const layout1 = (children:React.ReactNode) => (<html lang="en">
<body className={inter.className}>
    <>
    <Header />
    <Navbar />
    <>
    {children}
    </>

   <Footer />
  </>

</body>
</html>
)
const layout2 = (children:React.ReactNode) => (
<html lang="en">
<body className={inter.className}>
    <>
  {children}
  </>

</body>
</html>
)
export default function RootLayout({
  children,
  role = 'user',
}: {
  children: React.ReactNode;
  role?: 'user' | 'admin';
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {role === 'user' ? (
         layout1(children)
        ) : (
      layout2(children)
        )}
      </body>
    </html>
  );
}
