import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  role = 'user',
}: {
  children: React.ReactNode;
  role?: 'user' | 'admin';
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {role !== 'admin' && <Header />}
        {role !== 'admin' && <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
 